/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: [
    "bail",
    "character-entities",
    "decode-named-character-reference",
    "longest-streak",
    "mdast-util-from-markdown",
    "mdast-util-phrasing",
    "mdast-util-to-markdown",
    "mdast-util-to-string",
    "micromark",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-normalize-identifier",
    "remark-parse",
    "remark-stringify",
    "trough",
    "unified",
    "unist-util-is",
    "unist-util-stringify-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "vfile",
    "vfile-message",
    "zwitch",
  ],
};
